ignoreWorkspaceRootCheck: true

minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@antfu/eslint-config@9.4.1'
  - eslint-plugin-pnpm@1.9.1
  - pnpm-workspace-yaml@1.9.1

trustPolicy: no-downgrade
shellEmulator: true

allowBuilds:
  simple-git-hooks: true
